### ISSUE TITLE
rai_component_utilities.UserConfigError: ("Unable to load mlflow model from...

### ISSUE THREAD

**Issue by jingjiajie** [Azure/RAI-vNext-Preview#219]
When I tried to create the RAI dashboard, the job failed reported error:
![a](https://github.com/user-attachments/assets/a269b84d-c081-4c57-8035-7a85eb675e10)

Wait 30s for application insights async channel to flush
Traceback (most recent call last):
  File "/mnt/azureml/cr/j/100b64f038e64e8f8b7d0dc31fddebef/exe/wd/rai_component_utilities.py", line 147, in load_mlflow_model
    model = mlflow.pyfunc.load_model(model_uri)._model_impl
  File "/azureml-envs/responsibleai/lib/python3.8/site-packages/mlflow/pyfunc/__init__.py", line 680, in load_model
    model_impl = importlib.import_module(conf[MAIN])._load_pyfunc(data_path)
  File "/azureml-envs/responsibleai/lib/python3.8/site-packages/mlflow/sklearn/__init__.py", line 497, in _load_pyfunc
    _load_model_from_local_file(path=path, serialization_format=serialization_format)
  File "/azureml-envs/responsibleai/lib/python3.8/site-packages/mlflow/sklearn/__init__.py", line 454, in _load_model_from_local_file
    return cloudpickle.load(f)
  File "sklearn/tree/_tree.pyx", line 676, in sklearn.tree._tree.Tree.__setstate__
  File "sklearn/tree/_tree.pyx", line 1364, in sklearn.tree._tree._check_node_ndarray
ValueError: node array from the pickle has an incompatible dtype:
- expected: [('left_child', '<i8'), ('right_child', '<i8'), ('feature', '<i8'), ('threshold', '<f8'), ('impurity', '<f8'), ('n_node_samples', '<i8'), ('weighted_n_node_samples', '<f8')]
- got     : {'names': ['left_child', 'right_child', 'feature', 'threshold', 'impurity', 'n_node_samples', 'weighted_n_node_samples', 'missing_go_to_left'], 'formats': ['<i8', '<i8', '<i8', '<f8', '<f8', '<i8', '<f8', 'u1'], 'offsets': [0, 8, 16, 24, 32, 40, 48, 56], 'itemsize': 64}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/azureml/cr/j/100b64f038e64e8f8b7d0dc31fddebef/exe/wd/_telemetry/_loggerfactory.py", line 143, in wrapper
    return func(*args, **kwargs)
  File "create_rai_insights.py", line 180, in main
    model_estimator = load_mlflow_model(
  File "/mnt/azureml/cr/j/100b64f038e64e8f8b7d0dc31fddebef/exe/wd/rai_component_utilities.py", line 222, in load_mlflow_model
    raise UserConfigError(
rai_component_utilities.UserConfigError: ("Unable to load mlflow model from /mnt/azureml/cr/j/100b64f038e64e8f8b7d0dc31fddebef/cap/data-capability/wd/INPUT_model_input in current environment due to error:\nnode array from the pickle has an incompatible dtype:\n- expected: [('left_child', '<i8'), ('right_child', '<i8'), ('feature', '<i8'), ('threshold', '<f8'), ('impurity', '<f8'), ('n_node_samples', '<i8'), ('weighted_n_node_samples', '<f8')]\n- got     : {'names': ['left_child', 'right_child', 'feature', 'threshold', 'impurity', 'n_node_samples', 'weighted_n_node_samples', 'missing_go_to_left'], 'formats': ['<i8', '<i8', '<i8', '<f8', '<f8', '<i8', '<f8', 'u1'], 'offsets': [0, 8, 16, 24, 32, 40, 48, 56], 'itemsize': 64}", ValueError("node array from the pickle has an incompatible dtype:\n- expected: [('left_child', '<i8'), ('right_child', '<i8'), ('feature', '<i8'), ('threshold', '<f8'), ('impurity', '<f8'), ('n_node_samples', '<i8'), ('weighted_n_node_samples', '<f8')]\n- got     : {'names': ['left_child', 'right_child', 'feature', 'threshold', 'impurity', 'n_node_samples', 'weighted_n_node_samples', 'missing_go_to_left'], 'formats': ['<i8', '<i8', '<i8', '<f8', '<f8', '<i8', '<f8', 'u1'], 'offsets': [0, 8, 16, 24, 32, 40, 48, 56], 'itemsize': 64}"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "create_rai_insights.py", line 236, in <module>
    main(args)
  File "/mnt/azureml/cr/j/100b64f038e64e8f8b7d0dc31fddebef/exe/wd/_telemetry/_loggerfactory.py", line 146, in wrapper
    if isinstance(al, logger):
TypeError: isinstance() arg 2 must be a type or tuple of types

Attached is the full logs:
[Job_create_rai_job_OutputsAndLogs.zip](https://github.com/user-attachments/files/17013590/Job_create_rai_job_OutputsAndLogs.zip)

Can anyone help?

**Comment by jingjiajie** [comment]
After I fixed the version conflicts warned in the log, it finally succeeded.
